### ISSUE TITLE
sender_id' cannot be null

### ISSUE THREAD

**Issue by filtration** [hootlex/laravel-friendships#75] opened 2017-01-14 14:51 UTC
I am creating the user vairable, and passing it through to befriend, but am receiving the error below, this is my code:

    public function getManageFriendRequests($id, $type, User $user)
    {
        $recipient = $user->find($id);
        $sender = Auth::user();
 
        if($type == 'accept'){
            $user->acceptFriendRequest($recipient);
        }
        elseif($type == 'reject'){
            $user->denyFriendRequest($recipient);
        }
        elseif($type == 'add'){
            $user->befriend($recipient);
        }

    }

QueryException in Connection.php line 770:
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'sender_id' cannot be null (SQL: insert into `friendships` (`recipient_id`, `recipient_type`, `status`, `sender_type`, `sender_id`, `updated_at`, `created_at`) values (1, App\User, 0, App\User, , 2017-01-14 14:49:46, 2017-01-14 14:49:46))

What is causing this error? I'm sure I've followed all the instruction?

**Comment by hootlex** [comment] 2017-02-09 14:46
Have you managed to fix that? I think you should use `User::find($id)` instead.

**Comment by stephane-monnot** [comment] 2017-03-28 16:15
Or `$sender` instead of `$user` for : 
`$sender->acceptFriendRequest($recipient);`
`$sender->denyFriendRequest($recipient);`
`$sender->befriend($recipient);`

Not a bug, @hootlex Maybe we can close this issue ?

**Comment by hootlex** [comment] 2017-03-28 22:43
@stephane-monnot yes, thanks for the reminder.

**Closed by hootlex** 2017-03-28 22:43 UTC
